### PR TITLE
Compatibility with Nette 3.0 [WIP]

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Thanks, released as 2.0.0-rc1

**Comment by dg** [comment]
Oh, you are really fast, it was just WIP :-)

**Comment by dg** [comment]
@JanTvrdik  What do you think about adding StaticRouter directly into Nette?

**Comment by JanTvrdik** [comment]
I'll be ok with that. Any plans to automatically compile lots of simple routes to use StaticRouter?

**Pull request closed without merging**
